# Fundamentals of NumPy

This notebook aims to quickly walk you through the most fundamental bits of NumPy, including:
1. how to create/initiate 1D arrays and 2D matrices,
2. how to get/set the shape of numpy arrays,
3. and how to calculate the dot product of two NumPy arrays.

*This notebook is created by cherry-picking from [the official documents of NumPy](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html). Please refer to that page for more information.*

In [1]:
import numpy as np

## 1. `ndarray` in NumPy

NumPy’s main object is the homogeneous multidimensional array (`ndarray`). It is a table of elements (usually numbers), all of the same type, indexed by a tuple of positive integers.

A list of elements can be expressed as an `ndarray` of rank 1, i.e. a 1D array; a matrix can be expressed as an `ndarray` of rank 2.

Here lists some important attributes of `ndarray`:

* **`ndarray.ndim`**: the rank of the `ndarray`. For instance, a matrix has a rank of 2.
* **`ndarray.shape`**: the dimensions of the `ndarray` as a tuple of integers. For an array having 10 elements, the shape is `(10,)` (**note the trailing comma**, not the same as `(10, 1)`); for a matrix having 20 rows and 30 columns, the shape is `(20, 30)`.
* **`ndarray.size`**: the total number of elements in the `ndarray`, which is equal to the product of the dimensions.
* **`ndarray.dtype`**: an object describing the type of the elements in the array.

In [2]:
arr = np.array(range(1, 10))
print('arr\t\t', arr)
print('arr.ndim\t', arr.ndim)
print('arr.shape\t', arr.shape)
print('arr.size\t', arr.size)
print('arr.dtype\t', arr.dtype)

arr		 [1 2 3 4 5 6 7 8 9]
arr.ndim	 1
arr.shape	 (9,)
arr.size	 9
arr.dtype	 int32


In [ ]:
arr.

## 2. Array Creation

There are several ways to create `ndarray`s.

### 2.1 Using the `array` function

You can create a 1D `ndarray` from an existing list/array easily using the `array` function.

In [9]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

Note that there is only one argument. So never do this:

In [10]:
np.array(1, 2, 3, 4)

ValueError: only 2 non-keyword arguments accepted

To create a matrix, call `array` on a sequence of sequence.

In [14]:
x = np.array([[1, 2], [3, 4], [5, 6]])
x

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
x.shape

(3, 2)

### 2.2 Using `zeros`, `ones`, `empty`

When the contents of the array to be created are unknown, but its dimensions are known, use one of `zeros`, `ones`, `empty`.

In [6]:
np.zeros((2, 3))  # the elements are explicitly initialized to zeros

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [7]:
np.ones((2, 3))  # the elements are explicitly initialized to ones

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [8]:
np.empty((2, 3))  # the elements are not explicitly initialized; expect random values

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

The default `dtype` is `numpy.float64` for these functions.

### 2.3 Using `arange`, `linspace`

Akin to `range` in Python, `arange` in NumPy returns a sequence of numbers in a `ndarray`. Use the `dtype` parameter to change the type, or use `astype()` function to cast into another type.  

In [ ]:
np.arange(1, 3, 0.2)

Due to the finite precision of floating point numbers, however, it's better to use `linspace` when we are trying to create a sequence of floating point numbers, specifying how many elements we want, instead of the `step`.

In [ ]:
np.linspace(1, 3, 7)

## 3. Playing with the Shapes of `ndarray`s

In [24]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

### 3.1 How to Get the Shape of an `ndarray`

In [18]:
arr.shape

(9,)

### 3.2 How to Reshape the `ndarray`:

In [19]:
arr.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

The `reshape` function returns a new `ndarray` with the shape changed without modifying the original one.

In [20]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
arr.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

To directly modify the shape of an `ndarray`:

In [ ]:
arr.shape = (3, 3)
arr

## 4. Basic Operations

### 4.1 Arithmetic Operators

Arithmetic operators on `ndarray`s apply elementwise (so the operation is *vectorized*). A new `ndarray` will be created to hold the result.

In [26]:
arr = np.array([1, 2])

In [27]:
arr + 1

array([2, 3])

In [28]:
arr * 2

array([2, 4])

In [29]:
arr ** 2

array([1, 4])

### 4.2 Dot Products

Given two `ndarray`s with proper shapes:

In [30]:
a = np.array([1, 2])
a

array([1, 2])

In [31]:
b = np.array([[1], [2]])
b

array([[1],
       [2]])

To calculate the dot product, the sentence in the following cell is intuitive but **WRONG**:

In [32]:
a * b  # calculating elementwise product!

array([[1, 2],
       [2, 4]])

To correctly calculate the dot products of two `ndarray`s, use `numpy.dot` or the `dot` function on the `ndarray` object.

In [33]:
a.dot(b)

array([5])

In [34]:
np.dot(a, b)

array([5])

Both ways create a new `ndarray` to hold the results without modifying the original ones.